use ATINChamCong
go

--Create proc spInsertNguoi
--@MaNguoi int,
--@MaDinhDanh varchar(50),
--@HoTen nvarchar(100),
--@PhongBan int,
--@ChucVu int,
--@KhuVuc int,
--@NgaySinh date,
--@GioiTinh int,
--@SoDienThoai varchar(20),
--@Email varchar(50),
--@AnhDaiDien varchar(200),
--@TrinhDo int,
--@SoTheCanCuoc varchar(50),
--@NgayCapTCC date,
--@NoiCapTCC nvarchar(50),
--@DanToc int,
--@TonGiao int,
--@QuocTich int,
--@TinhTrangHonNhan int,
--@SoBangLaiXeMay varchar(50),
--@NgayCapBLXM date,
--@NoiCapBLXM nvarchar(150),
--@SoBangLaiOto varchar(50),
--@NgayCapBLXO date,
--@NoiCapBLXO nvarchar(150),
--@DiaChiThuongTru nvarchar(150),
--@DiaChiTamTru varchar(20),
--@NgayNhanViec date,
--@NgayThoiViec date,
--@SuDungVanTay bit,
--@SuDungTheTu bit,
--@SuDungKhuonMat bit,
--@ThoiGianDangKy date,
--@ThoiGianCapNhat date,
--@GhiChu nvarchar(150),
--@TrangThaiHoatDong int
--as
--begin
--insert into 
--Nguoi(
--MaNguoi,
--MaDinhDanh,
--HoTen,
--PhongBan,
--ChucVu,
--KhuVuc ,
--NgaySinh,
--GioiTinh,
--SoDienThoai ,
--Email ,
--AnhDaiDien ,
--TrinhDo ,
--SoTheCanCuoc ,
--NgayCapTCC ,
--NoiCapTCC ,
--DanToc ,
--TonGiao ,
--QuocTich ,
--TinhTrangHonNhan ,
--SoBangLaiXeMay ,
--NgayCapBLXM ,
--NoiCapBLXM ,
--SoBangLaiOto ,
--NgayCapBLXO ,
--NoiCapBLXO ,
--DiaChiThuongTru ,
--DiaChiTamTru ,
--NgayNhanViec ,
--NgayThoiViec ,
--SuDungVanTay ,
--SuDungTheTu ,
--SuDungKhuonMat ,
--ThoiGianDangKy ,
--ThoiGianCapNhat ,
--GhiChu ,
--TrangThaiHoatDong 
--)
--values
--(
--@MaNguoi,
--@MaDinhDanh ,
--@HoTen ,
--@PhongBan ,
--@ChucVu ,
--@KhuVuc ,
--@NgaySinh ,
--@GioiTinh ,
--@SoDienThoai ,
--@Email ,
--@AnhDaiDien ,
--@TrinhDo ,
--@SoTheCanCuoc ,
--@NgayCapTCC ,
--@NoiCapTCC ,
--@DanToc ,
--@TonGiao ,
--@QuocTich ,
--@TinhTrangHonNhan ,
--@SoBangLaiXeMay ,
--@NgayCapBLXM ,
--@NoiCapBLXM ,
--@SoBangLaiOto ,
--@NgayCapBLXO ,
--@NoiCapBLXO ,
--@DiaChiThuongTru ,
--@DiaChiTamTru ,
--@NgayNhanViec ,
--@NgayThoiViec ,
--@SuDungVanTay ,
--@SuDungTheTu ,
--@SuDungKhuonMat ,
--@ThoiGianDangKy ,
--@ThoiGianCapNhat ,
--@GhiChu ,
--@TrangThaiHoatDong
--)
--end
--go

--Create proc spUpdateNguoi
--@MaNguoiChon int,
--@MaNguoi int,
--@MaDinhDanh varchar(50),
--@HoTen nvarchar(100),
--@PhongBan int,
--@ChucVu int,
--@KhuVuc int,
--@NgaySinh date,
--@GioiTinh int,
--@SoDienThoai varchar(20),
--@Email varchar(50),
--@AnhDaiDien varchar(200),
--@TrinhDo int,
--@SoTheCanCuoc varchar(50),
--@NgayCapTCC date,
--@NoiCapTCC nvarchar(50),
--@DanToc int,
--@TonGiao int,
--@QuocTich int,
--@TinhTrangHonNhan int,
--@SoBangLaiXeMay varchar(50),
--@NgayCapBLXM date,
--@NoiCapBLXM nvarchar(150),
--@SoBangLaiOto varchar(50),
--@NgayCapBLXO date,
--@NoiCapBLXO nvarchar(150),
--@DiaChiThuongTru nvarchar(150),
--@DiaChiTamTru varchar(20),
--@NgayNhanViec date,
--@NgayThoiViec date,
--@SuDungVanTay bit,
--@SuDungTheTu bit,
--@SuDungKhuonMat bit,
--@ThoiGianDangKy date,
--@ThoiGianCapNhat date,
--@GhiChu nvarchar(150),
--@TrangThaiHoatDong int
--as
--begin
--update Nguoi
--set
--MaNguoi = @MaNguoi,
--MaDinhDanh = @MaDinhDanh,
--HoTen =@HoTen,
--PhongBan =@PhongBan,
--ChucVu = @ChucVu,
--KhuVuc =@KhuVuc,
--NgaySinh=@NgaySinh,
--GioiTinh=@GioiTinh,
--SoDienThoai =@SoDienThoai,
--Email =@Email,
--AnhDaiDien =@AnhDaiDien,
--TrinhDo =@TrinhDo,
--SoTheCanCuoc =@SoTheCanCuoc,
--NgayCapTCC =@NgayCapTCC,
--NoiCapTCC =@NoiCapTCC,
--DanToc =@DanToc,
--TonGiao =@TonGiao,
--QuocTich =@QuocTich,
--TinhTrangHonNhan =@TinhTrangHonNhan,
--SoBangLaiXeMay =@SoBangLaiXeMay,
--NgayCapBLXM =@NgayCapBLXM,
--NoiCapBLXM =@NoiCapBLXM,
--SoBangLaiOto =@SoBangLaiOto,
--NgayCapBLXO =@NgayCapBLXO,
--NoiCapBLXO =@NoiCapBLXO,
--DiaChiThuongTru =@DiaChiThuongTru,
--DiaChiTamTru =@DiaChiTamTru,
--NgayNhanViec =@NgayNhanViec,
--NgayThoiViec =@NgayThoiViec,
--SuDungVanTay =@SuDungVanTay,
--SuDungTheTu =@SuDungTheTu,
--SuDungKhuonMat =@SuDungKhuonMat,
--ThoiGianDangKy =@ThoiGianDangKy,
--ThoiGianCapNhat =@ThoiGianCapNhat,
--GhiChu =@GhiChu,
--TrangThaiHoatDong=@TrangThaiHoatDong 

--where MaNguoi = @MaNguoiChon
--end
--go

--Create proc spDeleteNguoi
--@MaNguoi int
--as
--begin
--delete
--from Nguoi
--where MaNguoi = @MaNguoi
--end
--go

Create or Alter proc spGetAllNguoi
as
begin
Select*
from Nguoi
end
go

--Create proc spGetNguoi
--@MaNguoi int
--as
--begin
--select*
--from Nguoi
--where MaNguoi = @MaNguoi
--end
--go