//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATINChamCongEntities : DbContext
    {
        public ATINChamCongEntities()
            : base("name=ATINChamCongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CacLoaiVang> CacLoaiVangs { get; set; }
        public virtual DbSet<CaLamViec> CaLamViecs { get; set; }
        public virtual DbSet<ChamCong> ChamCongs { get; set; }
        public virtual DbSet<ChamCongChiTiet> ChamCongChiTiets { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CongTyKhuVuc> CongTyKhuVucs { get; set; }
        public virtual DbSet<DangKyNghiPhep> DangKyNghiPheps { get; set; }
        public virtual DbSet<DangKyTangCa> DangKyTangCas { get; set; }
        public virtual DbSet<DanToc> DanTocs { get; set; }
        public virtual DbSet<KhuonMat> KhuonMats { get; set; }
        public virtual DbSet<KyHieuCacLoaiVang> KyHieuCacLoaiVangs { get; set; }
        public virtual DbSet<KyHieuChamCong> KyHieuChamCongs { get; set; }
        public virtual DbSet<LichSuSuaDuLieuChamCong> LichSuSuaDuLieuChamCongs { get; set; }
        public virtual DbSet<LichTrinh> LichTrinhs { get; set; }
        public virtual DbSet<LichTrinhNam> LichTrinhNams { get; set; }
        public virtual DbSet<LichTrinhNangCao> LichTrinhNangCaos { get; set; }
        public virtual DbSet<LichTrinhThang> LichTrinhThangs { get; set; }
        public virtual DbSet<LichTrinhTuan> LichTrinhTuans { get; set; }
        public virtual DbSet<LoaiChamCong> LoaiChamCongs { get; set; }
        public virtual DbSet<LoaiHopDong> LoaiHopDongs { get; set; }
        public virtual DbSet<LoaiNghiPhep> LoaiNghiPheps { get; set; }
        public virtual DbSet<MapLichTrinhNangCao> MapLichTrinhNangCaos { get; set; }
        public virtual DbSet<MayNhanDang> MayNhanDangs { get; set; }
        public virtual DbSet<NgayNghiLe> NgayNghiLes { get; set; }
        public virtual DbSet<NgayPhepNhanVien> NgayPhepNhanViens { get; set; }
        public virtual DbSet<Nguoi> Nguois { get; set; }
        public virtual DbSet<NhatKy> NhatKies { get; set; }
        public virtual DbSet<PhanQuyenNhanDang> PhanQuyenNhanDangs { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<SapXepLichTrinh> SapXepLichTrinhs { get; set; }
        public virtual DbSet<SapXepLichTrinhTam> SapXepLichTrinhTams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheTu> TheTus { get; set; }
        public virtual DbSet<TonGiao> TonGiaos { get; set; }
        public virtual DbSet<TrinhDoHocVan> TrinhDoHocVans { get; set; }
        public virtual DbSet<VanTay> VanTays { get; set; }
        public virtual DbSet<XepLoaiChamCong> XepLoaiChamCongs { get; set; }
        public virtual DbSet<ViewGioChiaHaiCot> ViewGioChiaHaiCots { get; set; }
        public virtual DbSet<ViewGioNguon> ViewGioNguons { get; set; }
        public virtual DbSet<ViewSapXepLichTrinh> ViewSapXepLichTrinhs { get; set; }
        public virtual DbSet<ViewThongTinNhanVien1> ViewThongTinNhanVien1 { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int spDeleteAllLichTrinhNamByLichTrinh_Month(string maLichTrinh, Nullable<int> month)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteAllLichTrinhNamByLichTrinh_Month", maLichTrinhParameter, monthParameter);
        }
    
        public virtual int spDeleteAllLichTrinhThangByLichTrinh(string maLichTrinh)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteAllLichTrinhThangByLichTrinh", maLichTrinhParameter);
        }
    
        public virtual int spDeleteAllLichTrinhTuanByLichTrinh(string maLichTrinh)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteAllLichTrinhTuanByLichTrinh", maLichTrinhParameter);
        }
    
        public virtual int spDeleteCaLamViec(string maCaLamViec)
        {
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteCaLamViec", maCaLamViecParameter);
        }
    
        public virtual int spDeleteLichTrinh(string maLichTrinh)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteLichTrinh", maLichTrinhParameter);
        }
    
        public virtual int spDeleteLichTrinhNam(string maLichTrinh, string maCaLamViec, Nullable<int> date, Nullable<int> month)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteLichTrinhNam", maLichTrinhParameter, maCaLamViecParameter, dateParameter, monthParameter);
        }
    
        public virtual int spDeleteLichTrinhThang(string maLichTrinh, string maCaLamViec, Nullable<int> date)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteLichTrinhThang", maLichTrinhParameter, maCaLamViecParameter, dateParameter);
        }
    
        public virtual int spDeleteLichTrinhTuan(string maLichTrinh, string maCaLamViec, Nullable<int> dateInWeek)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var dateInWeekParameter = dateInWeek.HasValue ?
                new ObjectParameter("DateInWeek", dateInWeek) :
                new ObjectParameter("DateInWeek", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteLichTrinhTuan", maLichTrinhParameter, maCaLamViecParameter, dateInWeekParameter);
        }
    
        public virtual int spDeleteMapLichTrinhNangCao(string maLichTrinh, string maLichTrinhNangCao)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maLichTrinhNangCaoParameter = maLichTrinhNangCao != null ?
                new ObjectParameter("MaLichTrinhNangCao", maLichTrinhNangCao) :
                new ObjectParameter("MaLichTrinhNangCao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteMapLichTrinhNangCao", maLichTrinhParameter, maLichTrinhNangCaoParameter);
        }
    
        public virtual int spDeletePhongBan(Nullable<int> maPhongBan)
        {
            var maPhongBanParameter = maPhongBan.HasValue ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeletePhongBan", maPhongBanParameter);
        }
    
        public virtual int spDeleteSapXepLichTrinh(Nullable<int> maSapXep)
        {
            var maSapXepParameter = maSapXep.HasValue ?
                new ObjectParameter("MaSapXep", maSapXep) :
                new ObjectParameter("MaSapXep", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteSapXepLichTrinh", maSapXepParameter);
        }
    
        public virtual int spDeleteSapXepLichTrinhTam(Nullable<int> maLichTrinhTam)
        {
            var maLichTrinhTamParameter = maLichTrinhTam.HasValue ?
                new ObjectParameter("MaLichTrinhTam", maLichTrinhTam) :
                new ObjectParameter("MaLichTrinhTam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteSapXepLichTrinhTam", maLichTrinhTamParameter);
        }
    
        public virtual ObjectResult<CaLamViec> spGetAllCaLamViec()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CaLamViec>("spGetAllCaLamViec");
        }
    
        public virtual ObjectResult<CaLamViec> spGetAllCaLamViec(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CaLamViec>("spGetAllCaLamViec", mergeOption);
        }
    
        public virtual ObjectResult<ChucVu> spGetAllChucVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChucVu>("spGetAllChucVu");
        }
    
        public virtual ObjectResult<ChucVu> spGetAllChucVu(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChucVu>("spGetAllChucVu", mergeOption);
        }
    
        public virtual ObjectResult<KyHieuCacLoaiVang> spGetAllKyHieuCacLoaiVang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KyHieuCacLoaiVang>("spGetAllKyHieuCacLoaiVang");
        }
    
        public virtual ObjectResult<KyHieuCacLoaiVang> spGetAllKyHieuCacLoaiVang(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KyHieuCacLoaiVang>("spGetAllKyHieuCacLoaiVang", mergeOption);
        }
    
        public virtual ObjectResult<KyHieuChamCong> spGetAllKyHieuChamCong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KyHieuChamCong>("spGetAllKyHieuChamCong");
        }
    
        public virtual ObjectResult<KyHieuChamCong> spGetAllKyHieuChamCong(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KyHieuChamCong>("spGetAllKyHieuChamCong", mergeOption);
        }
    
        public virtual ObjectResult<LichTrinh> spGetAllLichTrinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinh>("spGetAllLichTrinh");
        }
    
        public virtual ObjectResult<LichTrinh> spGetAllLichTrinh(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinh>("spGetAllLichTrinh", mergeOption);
        }
    
        public virtual ObjectResult<Nguoi> spGetAllNguoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nguoi>("spGetAllNguoi");
        }
    
        public virtual ObjectResult<Nguoi> spGetAllNguoi(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nguoi>("spGetAllNguoi", mergeOption);
        }
    
        public virtual ObjectResult<PhongBan> spGetAllPhongBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan>("spGetAllPhongBan");
        }
    
        public virtual ObjectResult<PhongBan> spGetAllPhongBan(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan>("spGetAllPhongBan", mergeOption);
        }
    
        public virtual ObjectResult<SapXepLichTrinh> spGetAllSapXepLichTrinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinh>("spGetAllSapXepLichTrinh");
        }
    
        public virtual ObjectResult<SapXepLichTrinh> spGetAllSapXepLichTrinh(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinh>("spGetAllSapXepLichTrinh", mergeOption);
        }
    
        public virtual ObjectResult<SapXepLichTrinhTam> spGetAllSapXepLichTrinhTam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinhTam>("spGetAllSapXepLichTrinhTam");
        }
    
        public virtual ObjectResult<SapXepLichTrinhTam> spGetAllSapXepLichTrinhTam(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinhTam>("spGetAllSapXepLichTrinhTam", mergeOption);
        }
    
        public virtual ObjectResult<ViewGioChiaHaiCot> spGetAllViewGioChiaHaiCot(Nullable<int> maNhanVien, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewGioChiaHaiCot>("spGetAllViewGioChiaHaiCot", maNhanVienParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<ViewGioChiaHaiCot> spGetAllViewGioChiaHaiCot(Nullable<int> maNhanVien, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, MergeOption mergeOption)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewGioChiaHaiCot>("spGetAllViewGioChiaHaiCot", mergeOption, maNhanVienParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<ViewGioNguon> spGetAllViewGioNguonOrderByNgayGio(Nullable<int> maNhanVien, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewGioNguon>("spGetAllViewGioNguonOrderByNgayGio", maNhanVienParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<ViewGioNguon> spGetAllViewGioNguonOrderByNgayGio(Nullable<int> maNhanVien, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, MergeOption mergeOption)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewGioNguon>("spGetAllViewGioNguonOrderByNgayGio", mergeOption, maNhanVienParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<ViewThongTinNhanVien1> spGetAllViewThongTinNhanVien1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewThongTinNhanVien1>("spGetAllViewThongTinNhanVien1");
        }
    
        public virtual ObjectResult<ViewThongTinNhanVien1> spGetAllViewThongTinNhanVien1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewThongTinNhanVien1>("spGetAllViewThongTinNhanVien1", mergeOption);
        }
    
        public virtual ObjectResult<CaLamViec> spGetCaLamViec(string maCaLamViec)
        {
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CaLamViec>("spGetCaLamViec", maCaLamViecParameter);
        }
    
        public virtual ObjectResult<CaLamViec> spGetCaLamViec(string maCaLamViec, MergeOption mergeOption)
        {
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CaLamViec>("spGetCaLamViec", mergeOption, maCaLamViecParameter);
        }
    
        public virtual ObjectResult<LichTrinh> spGetLichTrinh(string maCaLamViec)
        {
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinh>("spGetLichTrinh", maCaLamViecParameter);
        }
    
        public virtual ObjectResult<LichTrinh> spGetLichTrinh(string maCaLamViec, MergeOption mergeOption)
        {
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinh>("spGetLichTrinh", mergeOption, maCaLamViecParameter);
        }
    
        public virtual ObjectResult<LichTrinhNam> spGetLichTrinhNamByLichTrinh(string maLichTrinh)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinhNam>("spGetLichTrinhNamByLichTrinh", maLichTrinhParameter);
        }
    
        public virtual ObjectResult<LichTrinhNam> spGetLichTrinhNamByLichTrinh(string maLichTrinh, MergeOption mergeOption)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinhNam>("spGetLichTrinhNamByLichTrinh", mergeOption, maLichTrinhParameter);
        }
    
        public virtual ObjectResult<LichTrinhThang> spGetLichTrinhThangByLichTrinh(string maLichTrinh)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinhThang>("spGetLichTrinhThangByLichTrinh", maLichTrinhParameter);
        }
    
        public virtual ObjectResult<LichTrinhThang> spGetLichTrinhThangByLichTrinh(string maLichTrinh, MergeOption mergeOption)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinhThang>("spGetLichTrinhThangByLichTrinh", mergeOption, maLichTrinhParameter);
        }
    
        public virtual ObjectResult<LichTrinhTuan> spGetLichTrinhTuanByLichTrinh(string maLichTrinh)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinhTuan>("spGetLichTrinhTuanByLichTrinh", maLichTrinhParameter);
        }
    
        public virtual ObjectResult<LichTrinhTuan> spGetLichTrinhTuanByLichTrinh(string maLichTrinh, MergeOption mergeOption)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LichTrinhTuan>("spGetLichTrinhTuanByLichTrinh", mergeOption, maLichTrinhParameter);
        }
    
        public virtual ObjectResult<MapLichTrinhNangCao> spGetMapLichTrinhNangCaoByLichTrinh(string maLichTrinh)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MapLichTrinhNangCao>("spGetMapLichTrinhNangCaoByLichTrinh", maLichTrinhParameter);
        }
    
        public virtual ObjectResult<MapLichTrinhNangCao> spGetMapLichTrinhNangCaoByLichTrinh(string maLichTrinh, MergeOption mergeOption)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MapLichTrinhNangCao>("spGetMapLichTrinhNangCaoByLichTrinh", mergeOption, maLichTrinhParameter);
        }
    
        public virtual ObjectResult<PhongBan> spGetPhongBan(Nullable<int> maPhongBan)
        {
            var maPhongBanParameter = maPhongBan.HasValue ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan>("spGetPhongBan", maPhongBanParameter);
        }
    
        public virtual ObjectResult<PhongBan> spGetPhongBan(Nullable<int> maPhongBan, MergeOption mergeOption)
        {
            var maPhongBanParameter = maPhongBan.HasValue ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhongBan>("spGetPhongBan", mergeOption, maPhongBanParameter);
        }
    
        public virtual ObjectResult<SapXepLichTrinh> spGetSapXepLichTrinhByNguoi(Nullable<int> maNguoi)
        {
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinh>("spGetSapXepLichTrinhByNguoi", maNguoiParameter);
        }
    
        public virtual ObjectResult<SapXepLichTrinh> spGetSapXepLichTrinhByNguoi(Nullable<int> maNguoi, MergeOption mergeOption)
        {
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinh>("spGetSapXepLichTrinhByNguoi", mergeOption, maNguoiParameter);
        }
    
        public virtual ObjectResult<SapXepLichTrinhTam> spGetSapXepLichTrinhTamByNguoi(Nullable<int> maNguoi)
        {
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinhTam>("spGetSapXepLichTrinhTamByNguoi", maNguoiParameter);
        }
    
        public virtual ObjectResult<SapXepLichTrinhTam> spGetSapXepLichTrinhTamByNguoi(Nullable<int> maNguoi, MergeOption mergeOption)
        {
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SapXepLichTrinhTam>("spGetSapXepLichTrinhTamByNguoi", mergeOption, maNguoiParameter);
        }
    
        public virtual ObjectResult<ViewSapXepLichTrinh> spGetViewSapXepLichTrinhByNguoi(Nullable<int> maNguoi)
        {
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewSapXepLichTrinh>("spGetViewSapXepLichTrinhByNguoi", maNguoiParameter);
        }
    
        public virtual ObjectResult<ViewSapXepLichTrinh> spGetViewSapXepLichTrinhByNguoi(Nullable<int> maNguoi, MergeOption mergeOption)
        {
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewSapXepLichTrinh>("spGetViewSapXepLichTrinhByNguoi", mergeOption, maNguoiParameter);
        }
    
        public virtual ObjectResult<ViewThongTinNhanVien1> spGetViewThongTinNhanVien1ByPhongBan(Nullable<int> maPhongBan)
        {
            var maPhongBanParameter = maPhongBan.HasValue ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewThongTinNhanVien1>("spGetViewThongTinNhanVien1ByPhongBan", maPhongBanParameter);
        }
    
        public virtual ObjectResult<ViewThongTinNhanVien1> spGetViewThongTinNhanVien1ByPhongBan(Nullable<int> maPhongBan, MergeOption mergeOption)
        {
            var maPhongBanParameter = maPhongBan.HasValue ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewThongTinNhanVien1>("spGetViewThongTinNhanVien1ByPhongBan", mergeOption, maPhongBanParameter);
        }
    
        public virtual int spInsertCaLamViec(string maCaLamViec, string tenCaLamViec, Nullable<System.TimeSpan> gioBatDauCa, Nullable<System.TimeSpan> gioKetThucCa, Nullable<System.TimeSpan> gioBatDauGiaiLao, Nullable<System.TimeSpan> gioKetThucGiaiLao, Nullable<int> tongGio, Nullable<int> diemCong, Nullable<System.TimeSpan> gioVaoSomNhatDuocTinhCa, Nullable<System.TimeSpan> gioVaoMuonNhatDuocTinhCa, Nullable<System.TimeSpan> gioRaMuonNhatDuocTinhCa, Nullable<System.TimeSpan> gioRaSomNhatDuocTinhCa, Nullable<int> khongCoGioRa, Nullable<int> khongCoGioVao, Nullable<bool> truGioDiTre, Nullable<int> thoiGianDiTreChoPhep, Nullable<bool> truGioVeSom, Nullable<int> thoiGianVeSomChoPhep, Nullable<bool> sDMucTangCaHienTai, Nullable<int> mucTangCaHienTai, Nullable<bool> sDMucTangCaCuoiTuan, Nullable<int> mucTangCaCuoiTuan, Nullable<bool> sDMucTangCaNgayLe, Nullable<int> mucTangCaNgayLe, Nullable<bool> sDTangCaTruocGLV, Nullable<int> tangCaTruocGLV, Nullable<bool> sDTangCaSauGLV, Nullable<int> tangCaSauGLV, Nullable<bool> sDTongGLVTinhTangCa, Nullable<int> tongGLVTinhTangCa, Nullable<int> gioiHanTCMucMot, Nullable<int> gioiHanTCMucHai, Nullable<bool> sDMucTangCaCuaTangCaCuoiTuan, Nullable<int> mucTangCaCuaTangCaCuoiTuan, Nullable<bool> sDMucTangCaCuaTangCaNgayLe, Nullable<int> mucTangCaCuaTangCaNgayLe, Nullable<int> gioiHanTCTruocGLV, Nullable<int> gioiHanTCSauGLV, Nullable<bool> caQuaDem, Nullable<System.TimeSpan> tachGioCaDemTu, Nullable<System.TimeSpan> tachGioCaDemDen)
        {
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var tenCaLamViecParameter = tenCaLamViec != null ?
                new ObjectParameter("TenCaLamViec", tenCaLamViec) :
                new ObjectParameter("TenCaLamViec", typeof(string));
    
            var gioBatDauCaParameter = gioBatDauCa.HasValue ?
                new ObjectParameter("GioBatDauCa", gioBatDauCa) :
                new ObjectParameter("GioBatDauCa", typeof(System.TimeSpan));
    
            var gioKetThucCaParameter = gioKetThucCa.HasValue ?
                new ObjectParameter("GioKetThucCa", gioKetThucCa) :
                new ObjectParameter("GioKetThucCa", typeof(System.TimeSpan));
    
            var gioBatDauGiaiLaoParameter = gioBatDauGiaiLao.HasValue ?
                new ObjectParameter("GioBatDauGiaiLao", gioBatDauGiaiLao) :
                new ObjectParameter("GioBatDauGiaiLao", typeof(System.TimeSpan));
    
            var gioKetThucGiaiLaoParameter = gioKetThucGiaiLao.HasValue ?
                new ObjectParameter("GioKetThucGiaiLao", gioKetThucGiaiLao) :
                new ObjectParameter("GioKetThucGiaiLao", typeof(System.TimeSpan));
    
            var tongGioParameter = tongGio.HasValue ?
                new ObjectParameter("TongGio", tongGio) :
                new ObjectParameter("TongGio", typeof(int));
    
            var diemCongParameter = diemCong.HasValue ?
                new ObjectParameter("DiemCong", diemCong) :
                new ObjectParameter("DiemCong", typeof(int));
    
            var gioVaoSomNhatDuocTinhCaParameter = gioVaoSomNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioVaoSomNhatDuocTinhCa", gioVaoSomNhatDuocTinhCa) :
                new ObjectParameter("GioVaoSomNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var gioVaoMuonNhatDuocTinhCaParameter = gioVaoMuonNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioVaoMuonNhatDuocTinhCa", gioVaoMuonNhatDuocTinhCa) :
                new ObjectParameter("GioVaoMuonNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var gioRaMuonNhatDuocTinhCaParameter = gioRaMuonNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioRaMuonNhatDuocTinhCa", gioRaMuonNhatDuocTinhCa) :
                new ObjectParameter("GioRaMuonNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var gioRaSomNhatDuocTinhCaParameter = gioRaSomNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioRaSomNhatDuocTinhCa", gioRaSomNhatDuocTinhCa) :
                new ObjectParameter("GioRaSomNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var khongCoGioRaParameter = khongCoGioRa.HasValue ?
                new ObjectParameter("KhongCoGioRa", khongCoGioRa) :
                new ObjectParameter("KhongCoGioRa", typeof(int));
    
            var khongCoGioVaoParameter = khongCoGioVao.HasValue ?
                new ObjectParameter("KhongCoGioVao", khongCoGioVao) :
                new ObjectParameter("KhongCoGioVao", typeof(int));
    
            var truGioDiTreParameter = truGioDiTre.HasValue ?
                new ObjectParameter("TruGioDiTre", truGioDiTre) :
                new ObjectParameter("TruGioDiTre", typeof(bool));
    
            var thoiGianDiTreChoPhepParameter = thoiGianDiTreChoPhep.HasValue ?
                new ObjectParameter("ThoiGianDiTreChoPhep", thoiGianDiTreChoPhep) :
                new ObjectParameter("ThoiGianDiTreChoPhep", typeof(int));
    
            var truGioVeSomParameter = truGioVeSom.HasValue ?
                new ObjectParameter("TruGioVeSom", truGioVeSom) :
                new ObjectParameter("TruGioVeSom", typeof(bool));
    
            var thoiGianVeSomChoPhepParameter = thoiGianVeSomChoPhep.HasValue ?
                new ObjectParameter("ThoiGianVeSomChoPhep", thoiGianVeSomChoPhep) :
                new ObjectParameter("ThoiGianVeSomChoPhep", typeof(int));
    
            var sDMucTangCaHienTaiParameter = sDMucTangCaHienTai.HasValue ?
                new ObjectParameter("SDMucTangCaHienTai", sDMucTangCaHienTai) :
                new ObjectParameter("SDMucTangCaHienTai", typeof(bool));
    
            var mucTangCaHienTaiParameter = mucTangCaHienTai.HasValue ?
                new ObjectParameter("MucTangCaHienTai", mucTangCaHienTai) :
                new ObjectParameter("MucTangCaHienTai", typeof(int));
    
            var sDMucTangCaCuoiTuanParameter = sDMucTangCaCuoiTuan.HasValue ?
                new ObjectParameter("SDMucTangCaCuoiTuan", sDMucTangCaCuoiTuan) :
                new ObjectParameter("SDMucTangCaCuoiTuan", typeof(bool));
    
            var mucTangCaCuoiTuanParameter = mucTangCaCuoiTuan.HasValue ?
                new ObjectParameter("MucTangCaCuoiTuan", mucTangCaCuoiTuan) :
                new ObjectParameter("MucTangCaCuoiTuan", typeof(int));
    
            var sDMucTangCaNgayLeParameter = sDMucTangCaNgayLe.HasValue ?
                new ObjectParameter("SDMucTangCaNgayLe", sDMucTangCaNgayLe) :
                new ObjectParameter("SDMucTangCaNgayLe", typeof(bool));
    
            var mucTangCaNgayLeParameter = mucTangCaNgayLe.HasValue ?
                new ObjectParameter("MucTangCaNgayLe", mucTangCaNgayLe) :
                new ObjectParameter("MucTangCaNgayLe", typeof(int));
    
            var sDTangCaTruocGLVParameter = sDTangCaTruocGLV.HasValue ?
                new ObjectParameter("SDTangCaTruocGLV", sDTangCaTruocGLV) :
                new ObjectParameter("SDTangCaTruocGLV", typeof(bool));
    
            var tangCaTruocGLVParameter = tangCaTruocGLV.HasValue ?
                new ObjectParameter("TangCaTruocGLV", tangCaTruocGLV) :
                new ObjectParameter("TangCaTruocGLV", typeof(int));
    
            var sDTangCaSauGLVParameter = sDTangCaSauGLV.HasValue ?
                new ObjectParameter("SDTangCaSauGLV", sDTangCaSauGLV) :
                new ObjectParameter("SDTangCaSauGLV", typeof(bool));
    
            var tangCaSauGLVParameter = tangCaSauGLV.HasValue ?
                new ObjectParameter("TangCaSauGLV", tangCaSauGLV) :
                new ObjectParameter("TangCaSauGLV", typeof(int));
    
            var sDTongGLVTinhTangCaParameter = sDTongGLVTinhTangCa.HasValue ?
                new ObjectParameter("SDTongGLVTinhTangCa", sDTongGLVTinhTangCa) :
                new ObjectParameter("SDTongGLVTinhTangCa", typeof(bool));
    
            var tongGLVTinhTangCaParameter = tongGLVTinhTangCa.HasValue ?
                new ObjectParameter("TongGLVTinhTangCa", tongGLVTinhTangCa) :
                new ObjectParameter("TongGLVTinhTangCa", typeof(int));
    
            var gioiHanTCMucMotParameter = gioiHanTCMucMot.HasValue ?
                new ObjectParameter("GioiHanTCMucMot", gioiHanTCMucMot) :
                new ObjectParameter("GioiHanTCMucMot", typeof(int));
    
            var gioiHanTCMucHaiParameter = gioiHanTCMucHai.HasValue ?
                new ObjectParameter("GioiHanTCMucHai", gioiHanTCMucHai) :
                new ObjectParameter("GioiHanTCMucHai", typeof(int));
    
            var sDMucTangCaCuaTangCaCuoiTuanParameter = sDMucTangCaCuaTangCaCuoiTuan.HasValue ?
                new ObjectParameter("SDMucTangCaCuaTangCaCuoiTuan", sDMucTangCaCuaTangCaCuoiTuan) :
                new ObjectParameter("SDMucTangCaCuaTangCaCuoiTuan", typeof(bool));
    
            var mucTangCaCuaTangCaCuoiTuanParameter = mucTangCaCuaTangCaCuoiTuan.HasValue ?
                new ObjectParameter("MucTangCaCuaTangCaCuoiTuan", mucTangCaCuaTangCaCuoiTuan) :
                new ObjectParameter("MucTangCaCuaTangCaCuoiTuan", typeof(int));
    
            var sDMucTangCaCuaTangCaNgayLeParameter = sDMucTangCaCuaTangCaNgayLe.HasValue ?
                new ObjectParameter("SDMucTangCaCuaTangCaNgayLe", sDMucTangCaCuaTangCaNgayLe) :
                new ObjectParameter("SDMucTangCaCuaTangCaNgayLe", typeof(bool));
    
            var mucTangCaCuaTangCaNgayLeParameter = mucTangCaCuaTangCaNgayLe.HasValue ?
                new ObjectParameter("MucTangCaCuaTangCaNgayLe", mucTangCaCuaTangCaNgayLe) :
                new ObjectParameter("MucTangCaCuaTangCaNgayLe", typeof(int));
    
            var gioiHanTCTruocGLVParameter = gioiHanTCTruocGLV.HasValue ?
                new ObjectParameter("GioiHanTCTruocGLV", gioiHanTCTruocGLV) :
                new ObjectParameter("GioiHanTCTruocGLV", typeof(int));
    
            var gioiHanTCSauGLVParameter = gioiHanTCSauGLV.HasValue ?
                new ObjectParameter("GioiHanTCSauGLV", gioiHanTCSauGLV) :
                new ObjectParameter("GioiHanTCSauGLV", typeof(int));
    
            var caQuaDemParameter = caQuaDem.HasValue ?
                new ObjectParameter("CaQuaDem", caQuaDem) :
                new ObjectParameter("CaQuaDem", typeof(bool));
    
            var tachGioCaDemTuParameter = tachGioCaDemTu.HasValue ?
                new ObjectParameter("TachGioCaDemTu", tachGioCaDemTu) :
                new ObjectParameter("TachGioCaDemTu", typeof(System.TimeSpan));
    
            var tachGioCaDemDenParameter = tachGioCaDemDen.HasValue ?
                new ObjectParameter("TachGioCaDemDen", tachGioCaDemDen) :
                new ObjectParameter("TachGioCaDemDen", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertCaLamViec", maCaLamViecParameter, tenCaLamViecParameter, gioBatDauCaParameter, gioKetThucCaParameter, gioBatDauGiaiLaoParameter, gioKetThucGiaiLaoParameter, tongGioParameter, diemCongParameter, gioVaoSomNhatDuocTinhCaParameter, gioVaoMuonNhatDuocTinhCaParameter, gioRaMuonNhatDuocTinhCaParameter, gioRaSomNhatDuocTinhCaParameter, khongCoGioRaParameter, khongCoGioVaoParameter, truGioDiTreParameter, thoiGianDiTreChoPhepParameter, truGioVeSomParameter, thoiGianVeSomChoPhepParameter, sDMucTangCaHienTaiParameter, mucTangCaHienTaiParameter, sDMucTangCaCuoiTuanParameter, mucTangCaCuoiTuanParameter, sDMucTangCaNgayLeParameter, mucTangCaNgayLeParameter, sDTangCaTruocGLVParameter, tangCaTruocGLVParameter, sDTangCaSauGLVParameter, tangCaSauGLVParameter, sDTongGLVTinhTangCaParameter, tongGLVTinhTangCaParameter, gioiHanTCMucMotParameter, gioiHanTCMucHaiParameter, sDMucTangCaCuaTangCaCuoiTuanParameter, mucTangCaCuaTangCaCuoiTuanParameter, sDMucTangCaCuaTangCaNgayLeParameter, mucTangCaCuaTangCaNgayLeParameter, gioiHanTCTruocGLVParameter, gioiHanTCSauGLVParameter, caQuaDemParameter, tachGioCaDemTuParameter, tachGioCaDemDenParameter);
        }
    
        public virtual int spInsertChucVu(string tenChucVu)
        {
            var tenChucVuParameter = tenChucVu != null ?
                new ObjectParameter("TenChucVu", tenChucVu) :
                new ObjectParameter("TenChucVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertChucVu", tenChucVuParameter);
        }
    
        public virtual int spInsertLichTrinh(string maLichTrinh, string tenLichTrinh, string loaiChuKy)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var tenLichTrinhParameter = tenLichTrinh != null ?
                new ObjectParameter("TenLichTrinh", tenLichTrinh) :
                new ObjectParameter("TenLichTrinh", typeof(string));
    
            var loaiChuKyParameter = loaiChuKy != null ?
                new ObjectParameter("LoaiChuKy", loaiChuKy) :
                new ObjectParameter("LoaiChuKy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertLichTrinh", maLichTrinhParameter, tenLichTrinhParameter, loaiChuKyParameter);
        }
    
        public virtual int spInsertLichTrinhNam(string maLichTrinh, string maCaLamViec, Nullable<int> date, Nullable<int> month)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertLichTrinhNam", maLichTrinhParameter, maCaLamViecParameter, dateParameter, monthParameter);
        }
    
        public virtual int spInsertLichTrinhThang(string maLichTrinh, string maCaLamViec, Nullable<int> date)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertLichTrinhThang", maLichTrinhParameter, maCaLamViecParameter, dateParameter);
        }
    
        public virtual int spInsertLichTrinhTuan(string maLichTrinh, string maCaLamViec, Nullable<int> dateInWeek)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var dateInWeekParameter = dateInWeek.HasValue ?
                new ObjectParameter("DateInWeek", dateInWeek) :
                new ObjectParameter("DateInWeek", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertLichTrinhTuan", maLichTrinhParameter, maCaLamViecParameter, dateInWeekParameter);
        }
    
        public virtual int spInsertMapLichTrinhNangCao(string maLichTrinh, string maLichTrinhNangCao)
        {
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maLichTrinhNangCaoParameter = maLichTrinhNangCao != null ?
                new ObjectParameter("MaLichTrinhNangCao", maLichTrinhNangCao) :
                new ObjectParameter("MaLichTrinhNangCao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertMapLichTrinhNangCao", maLichTrinhParameter, maLichTrinhNangCaoParameter);
        }
    
        public virtual int spInsertPhongBan(Nullable<int> maPhongBan, string tenPhongBan)
        {
            var maPhongBanParameter = maPhongBan.HasValue ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(int));
    
            var tenPhongBanParameter = tenPhongBan != null ?
                new ObjectParameter("TenPhongBan", tenPhongBan) :
                new ObjectParameter("TenPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertPhongBan", maPhongBanParameter, tenPhongBanParameter);
        }
    
        public virtual int spInsertSapXepLichTrinh(Nullable<int> maNguoi, string maLichTrinh)
        {
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertSapXepLichTrinh", maNguoiParameter, maLichTrinhParameter);
        }
    
        public virtual int spInsertSapxepLichTrinhTam(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maLichTrinh, Nullable<int> maNguoi)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertSapxepLichTrinhTam", tuNgayParameter, denNgayParameter, maLichTrinhParameter, maNguoiParameter);
        }
    
        public virtual int spUpdateCaLamViec(string maCaLamViecChon, string maCaLamViec, string tenCaLamViec, Nullable<System.TimeSpan> gioBatDauCa, Nullable<System.TimeSpan> gioKetThucCa, Nullable<System.TimeSpan> gioBatDauGiaiLao, Nullable<System.TimeSpan> gioKetThucGiaiLao, Nullable<int> tongGio, Nullable<int> diemCong, Nullable<System.TimeSpan> gioVaoSomNhatDuocTinhCa, Nullable<System.TimeSpan> gioVaoMuonNhatDuocTinhCa, Nullable<System.TimeSpan> gioRaMuonNhatDuocTinhCa, Nullable<System.TimeSpan> gioRaSomNhatDuocTinhCa, Nullable<int> khongCoGioRa, Nullable<int> khongCoGioVao, Nullable<bool> truGioDiTre, Nullable<int> thoiGianDiTreChoPhep, Nullable<bool> truGioVeSom, Nullable<int> thoiGianVeSomChoPhep, Nullable<bool> sDMucTangCaHienTai, Nullable<int> mucTangCaHienTai, Nullable<bool> sDMucTangCaCuoiTuan, Nullable<int> mucTangCaCuoiTuan, Nullable<bool> sDMucTangCaNgayLe, Nullable<int> mucTangCaNgayLe, Nullable<bool> sDTangCaTruocGLV, Nullable<int> tangCaTruocGLV, Nullable<bool> sDTangCaSauGLV, Nullable<int> tangCaSauGLV, Nullable<bool> sDTongGLVTinhTangCa, Nullable<int> tongGLVTinhTangCa, Nullable<int> gioiHanTCMucMot, Nullable<int> gioiHanTCMucHai, Nullable<bool> sDMucTangCaCuaTangCaCuoiTuan, Nullable<int> mucTangCaCuaTangCaCuoiTuan, Nullable<bool> sDMucTangCaCuaTangCaNgayLe, Nullable<int> mucTangCaCuaTangCaNgayLe, Nullable<int> gioiHanTCTruocGLV, Nullable<int> gioiHanTCSauGLV, Nullable<bool> caQuaDem, Nullable<System.TimeSpan> tachGioCaDemTu, Nullable<System.TimeSpan> tachGioCaDemDen)
        {
            var maCaLamViecChonParameter = maCaLamViecChon != null ?
                new ObjectParameter("MaCaLamViecChon", maCaLamViecChon) :
                new ObjectParameter("MaCaLamViecChon", typeof(string));
    
            var maCaLamViecParameter = maCaLamViec != null ?
                new ObjectParameter("MaCaLamViec", maCaLamViec) :
                new ObjectParameter("MaCaLamViec", typeof(string));
    
            var tenCaLamViecParameter = tenCaLamViec != null ?
                new ObjectParameter("TenCaLamViec", tenCaLamViec) :
                new ObjectParameter("TenCaLamViec", typeof(string));
    
            var gioBatDauCaParameter = gioBatDauCa.HasValue ?
                new ObjectParameter("GioBatDauCa", gioBatDauCa) :
                new ObjectParameter("GioBatDauCa", typeof(System.TimeSpan));
    
            var gioKetThucCaParameter = gioKetThucCa.HasValue ?
                new ObjectParameter("GioKetThucCa", gioKetThucCa) :
                new ObjectParameter("GioKetThucCa", typeof(System.TimeSpan));
    
            var gioBatDauGiaiLaoParameter = gioBatDauGiaiLao.HasValue ?
                new ObjectParameter("GioBatDauGiaiLao", gioBatDauGiaiLao) :
                new ObjectParameter("GioBatDauGiaiLao", typeof(System.TimeSpan));
    
            var gioKetThucGiaiLaoParameter = gioKetThucGiaiLao.HasValue ?
                new ObjectParameter("GioKetThucGiaiLao", gioKetThucGiaiLao) :
                new ObjectParameter("GioKetThucGiaiLao", typeof(System.TimeSpan));
    
            var tongGioParameter = tongGio.HasValue ?
                new ObjectParameter("TongGio", tongGio) :
                new ObjectParameter("TongGio", typeof(int));
    
            var diemCongParameter = diemCong.HasValue ?
                new ObjectParameter("DiemCong", diemCong) :
                new ObjectParameter("DiemCong", typeof(int));
    
            var gioVaoSomNhatDuocTinhCaParameter = gioVaoSomNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioVaoSomNhatDuocTinhCa", gioVaoSomNhatDuocTinhCa) :
                new ObjectParameter("GioVaoSomNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var gioVaoMuonNhatDuocTinhCaParameter = gioVaoMuonNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioVaoMuonNhatDuocTinhCa", gioVaoMuonNhatDuocTinhCa) :
                new ObjectParameter("GioVaoMuonNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var gioRaMuonNhatDuocTinhCaParameter = gioRaMuonNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioRaMuonNhatDuocTinhCa", gioRaMuonNhatDuocTinhCa) :
                new ObjectParameter("GioRaMuonNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var gioRaSomNhatDuocTinhCaParameter = gioRaSomNhatDuocTinhCa.HasValue ?
                new ObjectParameter("GioRaSomNhatDuocTinhCa", gioRaSomNhatDuocTinhCa) :
                new ObjectParameter("GioRaSomNhatDuocTinhCa", typeof(System.TimeSpan));
    
            var khongCoGioRaParameter = khongCoGioRa.HasValue ?
                new ObjectParameter("KhongCoGioRa", khongCoGioRa) :
                new ObjectParameter("KhongCoGioRa", typeof(int));
    
            var khongCoGioVaoParameter = khongCoGioVao.HasValue ?
                new ObjectParameter("KhongCoGioVao", khongCoGioVao) :
                new ObjectParameter("KhongCoGioVao", typeof(int));
    
            var truGioDiTreParameter = truGioDiTre.HasValue ?
                new ObjectParameter("TruGioDiTre", truGioDiTre) :
                new ObjectParameter("TruGioDiTre", typeof(bool));
    
            var thoiGianDiTreChoPhepParameter = thoiGianDiTreChoPhep.HasValue ?
                new ObjectParameter("ThoiGianDiTreChoPhep", thoiGianDiTreChoPhep) :
                new ObjectParameter("ThoiGianDiTreChoPhep", typeof(int));
    
            var truGioVeSomParameter = truGioVeSom.HasValue ?
                new ObjectParameter("TruGioVeSom", truGioVeSom) :
                new ObjectParameter("TruGioVeSom", typeof(bool));
    
            var thoiGianVeSomChoPhepParameter = thoiGianVeSomChoPhep.HasValue ?
                new ObjectParameter("ThoiGianVeSomChoPhep", thoiGianVeSomChoPhep) :
                new ObjectParameter("ThoiGianVeSomChoPhep", typeof(int));
    
            var sDMucTangCaHienTaiParameter = sDMucTangCaHienTai.HasValue ?
                new ObjectParameter("SDMucTangCaHienTai", sDMucTangCaHienTai) :
                new ObjectParameter("SDMucTangCaHienTai", typeof(bool));
    
            var mucTangCaHienTaiParameter = mucTangCaHienTai.HasValue ?
                new ObjectParameter("MucTangCaHienTai", mucTangCaHienTai) :
                new ObjectParameter("MucTangCaHienTai", typeof(int));
    
            var sDMucTangCaCuoiTuanParameter = sDMucTangCaCuoiTuan.HasValue ?
                new ObjectParameter("SDMucTangCaCuoiTuan", sDMucTangCaCuoiTuan) :
                new ObjectParameter("SDMucTangCaCuoiTuan", typeof(bool));
    
            var mucTangCaCuoiTuanParameter = mucTangCaCuoiTuan.HasValue ?
                new ObjectParameter("MucTangCaCuoiTuan", mucTangCaCuoiTuan) :
                new ObjectParameter("MucTangCaCuoiTuan", typeof(int));
    
            var sDMucTangCaNgayLeParameter = sDMucTangCaNgayLe.HasValue ?
                new ObjectParameter("SDMucTangCaNgayLe", sDMucTangCaNgayLe) :
                new ObjectParameter("SDMucTangCaNgayLe", typeof(bool));
    
            var mucTangCaNgayLeParameter = mucTangCaNgayLe.HasValue ?
                new ObjectParameter("MucTangCaNgayLe", mucTangCaNgayLe) :
                new ObjectParameter("MucTangCaNgayLe", typeof(int));
    
            var sDTangCaTruocGLVParameter = sDTangCaTruocGLV.HasValue ?
                new ObjectParameter("SDTangCaTruocGLV", sDTangCaTruocGLV) :
                new ObjectParameter("SDTangCaTruocGLV", typeof(bool));
    
            var tangCaTruocGLVParameter = tangCaTruocGLV.HasValue ?
                new ObjectParameter("TangCaTruocGLV", tangCaTruocGLV) :
                new ObjectParameter("TangCaTruocGLV", typeof(int));
    
            var sDTangCaSauGLVParameter = sDTangCaSauGLV.HasValue ?
                new ObjectParameter("SDTangCaSauGLV", sDTangCaSauGLV) :
                new ObjectParameter("SDTangCaSauGLV", typeof(bool));
    
            var tangCaSauGLVParameter = tangCaSauGLV.HasValue ?
                new ObjectParameter("TangCaSauGLV", tangCaSauGLV) :
                new ObjectParameter("TangCaSauGLV", typeof(int));
    
            var sDTongGLVTinhTangCaParameter = sDTongGLVTinhTangCa.HasValue ?
                new ObjectParameter("SDTongGLVTinhTangCa", sDTongGLVTinhTangCa) :
                new ObjectParameter("SDTongGLVTinhTangCa", typeof(bool));
    
            var tongGLVTinhTangCaParameter = tongGLVTinhTangCa.HasValue ?
                new ObjectParameter("TongGLVTinhTangCa", tongGLVTinhTangCa) :
                new ObjectParameter("TongGLVTinhTangCa", typeof(int));
    
            var gioiHanTCMucMotParameter = gioiHanTCMucMot.HasValue ?
                new ObjectParameter("GioiHanTCMucMot", gioiHanTCMucMot) :
                new ObjectParameter("GioiHanTCMucMot", typeof(int));
    
            var gioiHanTCMucHaiParameter = gioiHanTCMucHai.HasValue ?
                new ObjectParameter("GioiHanTCMucHai", gioiHanTCMucHai) :
                new ObjectParameter("GioiHanTCMucHai", typeof(int));
    
            var sDMucTangCaCuaTangCaCuoiTuanParameter = sDMucTangCaCuaTangCaCuoiTuan.HasValue ?
                new ObjectParameter("SDMucTangCaCuaTangCaCuoiTuan", sDMucTangCaCuaTangCaCuoiTuan) :
                new ObjectParameter("SDMucTangCaCuaTangCaCuoiTuan", typeof(bool));
    
            var mucTangCaCuaTangCaCuoiTuanParameter = mucTangCaCuaTangCaCuoiTuan.HasValue ?
                new ObjectParameter("MucTangCaCuaTangCaCuoiTuan", mucTangCaCuaTangCaCuoiTuan) :
                new ObjectParameter("MucTangCaCuaTangCaCuoiTuan", typeof(int));
    
            var sDMucTangCaCuaTangCaNgayLeParameter = sDMucTangCaCuaTangCaNgayLe.HasValue ?
                new ObjectParameter("SDMucTangCaCuaTangCaNgayLe", sDMucTangCaCuaTangCaNgayLe) :
                new ObjectParameter("SDMucTangCaCuaTangCaNgayLe", typeof(bool));
    
            var mucTangCaCuaTangCaNgayLeParameter = mucTangCaCuaTangCaNgayLe.HasValue ?
                new ObjectParameter("MucTangCaCuaTangCaNgayLe", mucTangCaCuaTangCaNgayLe) :
                new ObjectParameter("MucTangCaCuaTangCaNgayLe", typeof(int));
    
            var gioiHanTCTruocGLVParameter = gioiHanTCTruocGLV.HasValue ?
                new ObjectParameter("GioiHanTCTruocGLV", gioiHanTCTruocGLV) :
                new ObjectParameter("GioiHanTCTruocGLV", typeof(int));
    
            var gioiHanTCSauGLVParameter = gioiHanTCSauGLV.HasValue ?
                new ObjectParameter("GioiHanTCSauGLV", gioiHanTCSauGLV) :
                new ObjectParameter("GioiHanTCSauGLV", typeof(int));
    
            var caQuaDemParameter = caQuaDem.HasValue ?
                new ObjectParameter("CaQuaDem", caQuaDem) :
                new ObjectParameter("CaQuaDem", typeof(bool));
    
            var tachGioCaDemTuParameter = tachGioCaDemTu.HasValue ?
                new ObjectParameter("TachGioCaDemTu", tachGioCaDemTu) :
                new ObjectParameter("TachGioCaDemTu", typeof(System.TimeSpan));
    
            var tachGioCaDemDenParameter = tachGioCaDemDen.HasValue ?
                new ObjectParameter("TachGioCaDemDen", tachGioCaDemDen) :
                new ObjectParameter("TachGioCaDemDen", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateCaLamViec", maCaLamViecChonParameter, maCaLamViecParameter, tenCaLamViecParameter, gioBatDauCaParameter, gioKetThucCaParameter, gioBatDauGiaiLaoParameter, gioKetThucGiaiLaoParameter, tongGioParameter, diemCongParameter, gioVaoSomNhatDuocTinhCaParameter, gioVaoMuonNhatDuocTinhCaParameter, gioRaMuonNhatDuocTinhCaParameter, gioRaSomNhatDuocTinhCaParameter, khongCoGioRaParameter, khongCoGioVaoParameter, truGioDiTreParameter, thoiGianDiTreChoPhepParameter, truGioVeSomParameter, thoiGianVeSomChoPhepParameter, sDMucTangCaHienTaiParameter, mucTangCaHienTaiParameter, sDMucTangCaCuoiTuanParameter, mucTangCaCuoiTuanParameter, sDMucTangCaNgayLeParameter, mucTangCaNgayLeParameter, sDTangCaTruocGLVParameter, tangCaTruocGLVParameter, sDTangCaSauGLVParameter, tangCaSauGLVParameter, sDTongGLVTinhTangCaParameter, tongGLVTinhTangCaParameter, gioiHanTCMucMotParameter, gioiHanTCMucHaiParameter, sDMucTangCaCuaTangCaCuoiTuanParameter, mucTangCaCuaTangCaCuoiTuanParameter, sDMucTangCaCuaTangCaNgayLeParameter, mucTangCaCuaTangCaNgayLeParameter, gioiHanTCTruocGLVParameter, gioiHanTCSauGLVParameter, caQuaDemParameter, tachGioCaDemTuParameter, tachGioCaDemDenParameter);
        }
    
        public virtual int spUpdateKyHeuChamCong(Nullable<int> maKyHieu, string tenKyHieu, Nullable<bool> suDung)
        {
            var maKyHieuParameter = maKyHieu.HasValue ?
                new ObjectParameter("MaKyHieu", maKyHieu) :
                new ObjectParameter("MaKyHieu", typeof(int));
    
            var tenKyHieuParameter = tenKyHieu != null ?
                new ObjectParameter("TenKyHieu", tenKyHieu) :
                new ObjectParameter("TenKyHieu", typeof(string));
    
            var suDungParameter = suDung.HasValue ?
                new ObjectParameter("SuDung", suDung) :
                new ObjectParameter("SuDung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateKyHeuChamCong", maKyHieuParameter, tenKyHieuParameter, suDungParameter);
        }
    
        public virtual int spUpdateKyHieuCacLoaiVang(string maKyHieu, Nullable<bool> suDung, Nullable<bool> tinhCong)
        {
            var maKyHieuParameter = maKyHieu != null ?
                new ObjectParameter("MaKyHieu", maKyHieu) :
                new ObjectParameter("MaKyHieu", typeof(string));
    
            var suDungParameter = suDung.HasValue ?
                new ObjectParameter("SuDung", suDung) :
                new ObjectParameter("SuDung", typeof(bool));
    
            var tinhCongParameter = tinhCong.HasValue ?
                new ObjectParameter("TinhCong", tinhCong) :
                new ObjectParameter("TinhCong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateKyHieuCacLoaiVang", maKyHieuParameter, suDungParameter, tinhCongParameter);
        }
    
        public virtual int spUpdateLichTrinh(string maLichTrinhChon, string maLichTrinh, string tenLichTrinh, string loaiChuKy)
        {
            var maLichTrinhChonParameter = maLichTrinhChon != null ?
                new ObjectParameter("MaLichTrinhChon", maLichTrinhChon) :
                new ObjectParameter("MaLichTrinhChon", typeof(string));
    
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var tenLichTrinhParameter = tenLichTrinh != null ?
                new ObjectParameter("TenLichTrinh", tenLichTrinh) :
                new ObjectParameter("TenLichTrinh", typeof(string));
    
            var loaiChuKyParameter = loaiChuKy != null ?
                new ObjectParameter("LoaiChuKy", loaiChuKy) :
                new ObjectParameter("LoaiChuKy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateLichTrinh", maLichTrinhChonParameter, maLichTrinhParameter, tenLichTrinhParameter, loaiChuKyParameter);
        }
    
        public virtual int spUpdatePhongBan(Nullable<int> maPhongBan, string tenPhongBan)
        {
            var maPhongBanParameter = maPhongBan.HasValue ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(int));
    
            var tenPhongBanParameter = tenPhongBan != null ?
                new ObjectParameter("TenPhongBan", tenPhongBan) :
                new ObjectParameter("TenPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdatePhongBan", maPhongBanParameter, tenPhongBanParameter);
        }
    
        public virtual int spUpdateSapXepLichTrinh(Nullable<int> maSapXep, Nullable<int> maNguoi, string maLichTrinh)
        {
            var maSapXepParameter = maSapXep.HasValue ?
                new ObjectParameter("MaSapXep", maSapXep) :
                new ObjectParameter("MaSapXep", typeof(int));
    
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateSapXepLichTrinh", maSapXepParameter, maNguoiParameter, maLichTrinhParameter);
        }
    
        public virtual int spUpdateSapxepLichTrinhTam(Nullable<int> maLichTrinhTam, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maLichTrinh, Nullable<int> maNguoi)
        {
            var maLichTrinhTamParameter = maLichTrinhTam.HasValue ?
                new ObjectParameter("MaLichTrinhTam", maLichTrinhTam) :
                new ObjectParameter("MaLichTrinhTam", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maLichTrinhParameter = maLichTrinh != null ?
                new ObjectParameter("MaLichTrinh", maLichTrinh) :
                new ObjectParameter("MaLichTrinh", typeof(string));
    
            var maNguoiParameter = maNguoi.HasValue ?
                new ObjectParameter("MaNguoi", maNguoi) :
                new ObjectParameter("MaNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateSapxepLichTrinhTam", maLichTrinhTamParameter, tuNgayParameter, denNgayParameter, maLichTrinhParameter, maNguoiParameter);
        }
    }
}
