//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCongChiTiet
    {
        public int MaChamCongChiTiet { get; set; }
        public int MaChamCong { get; set; }
        public System.DateTime NgayChamCong { get; set; }
        public System.DateTime GioChamCong { get; set; }
        public string MaLoaiChamCong { get; set; }
        public int NguonThucHien { get; set; }
        public Nullable<int> MaThietBi { get; set; }
        public byte[] HinhChamCong { get; set; }
    
        public virtual ChamCong ChamCong { get; set; }
        public virtual LoaiChamCong LoaiChamCong { get; set; }
    }
}
