//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyTangCa
    {
        public int Id { get; set; }
        public int MaNhanVien { get; set; }
        public string MaDinhDanh { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public int GioBD { get; set; }
        public int PhutBD { get; set; }
        public int GioKT { get; set; }
        public int PhutKT { get; set; }
        public string GhiChu { get; set; }
        public bool DK { get; set; }
    
        public virtual Nguoi Nguoi { get; set; }
    }
}
