//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongLaoDong
    {
        public int MaHopDong { get; set; }
        public int MaNhanVien { get; set; }
        public string SoHopDong { get; set; }
        public string LoaiHopDong { get; set; }
        public Nullable<System.DateTime> NgayKyHopDong { get; set; }
        public string GhiChu { get; set; }
    }
}
