//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhaiBaoThoiGian
    {
        public string MaThoiGian { get; set; }
        public string ThoiGian { get; set; }
        public string NhomThoiGian { get; set; }
        public Nullable<int> SapXep { get; set; }
    }
}
