//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KyHieuCacLoaiVang
    {
        public string MaLoaiVang { get; set; }
        public string TenLoaiVang { get; set; }
        public string KyHieu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> TinhCong { get; set; }
    }
}
