//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThamSo
    {
        public int Id { get; set; }
        public string LoaiThamSo1 { get; set; }
        public string TenLoaiThamSo { get; set; }
        public string MoTa { get; set; }
    }
}
