//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG_KHO
    {
        public string MHTEN { get; set; }
        public string MHCODE { get; set; }
        public string KHOCODE { get; set; }
        public string KHOTEN { get; set; }
        public System.Guid KHOID { get; set; }
        public System.Guid MHID { get; set; }
        public decimal SOLUONG { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIABANLE { get; set; }
        public Nullable<decimal> GIABANBUON { get; set; }
        public Nullable<decimal> GIABAN1 { get; set; }
        public Nullable<decimal> GIABAN2 { get; set; }
        public Nullable<decimal> GIABAN3 { get; set; }
        public Nullable<decimal> SLONORDER { get; set; }
        public Nullable<decimal> SLTONDAU { get; set; }
        public Nullable<decimal> GVTONDAU { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<decimal> SLTANG { get; set; }
        public Nullable<decimal> SLGIAM { get; set; }
    }
}
