//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayNhanDang
    {
        public int MaMay { get; set; }
        public string TenMay { get; set; }
        public string SoSerial { get; set; }
        public string DiaChiMac { get; set; }
        public Nullable<double> TongBoNho { get; set; }
        public Nullable<double> BoNhoTrong { get; set; }
        public Nullable<int> SoLuongKhuonMat { get; set; }
        public Nullable<int> SoLuongTheTu { get; set; }
        public Nullable<int> SoLuongVanTay { get; set; }
        public Nullable<System.DateTime> NgayKichHoat { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhat { get; set; }
        public Nullable<int> ChuKyDongBo { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhauDangNhap { get; set; }
        public string MaKichHoat { get; set; }
        public Nullable<bool> KichHoatOnline { get; set; }
        public Nullable<bool> TrangThaiKichHoat { get; set; }
        public Nullable<bool> TrangThaiKetNoi { get; set; }
    }
}
