//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayNhanDang
    {
        public int MaMay { get; set; }
        public string TenMay { get; set; }
        public string SoSerial { get; set; }
        public int LoaiMay { get; set; }
        public string DiaChiIP { get; set; }
        public string DiaChiMac { get; set; }
        public string NhaSanXuat { get; set; }
        public string AnhThietBi { get; set; }
        public Nullable<double> TongBoNho { get; set; }
        public Nullable<double> BoNhoHienTai { get; set; }
        public Nullable<int> SoLuongDangKy { get; set; }
        public Nullable<System.DateTime> ThoiGianKichHoat { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhat { get; set; }
        public Nullable<int> TuDongDongBo { get; set; }
        public Nullable<int> ThoiGianDongBo { get; set; }
        public Nullable<int> LuuAnhNhanDang { get; set; }
        public string TaiKhoanDangNhap { get; set; }
        public string MatKhauDangNhap { get; set; }
        public string MaKichHoat { get; set; }
        public Nullable<int> TrangThaiKetNoi { get; set; }
        public int TrangThaiHoatDong { get; set; }
    }
}
