//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKy
    {
        public int MaNhatKy { get; set; }
        public int MaNguoi { get; set; }
        public int MaKhuonMat { get; set; }
        public int MaTheTu { get; set; }
        public int MaVanTay { get; set; }
        public string AnhKhuonMat { get; set; }
        public byte[] ThuocTinhKhuonMat { get; set; }
        public Nullable<double> DiemSoSanh { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<System.DateTime> ThoiGianDienRa { get; set; }
        public string MaThietBi { get; set; }
        public string ThongBao { get; set; }
        public Nullable<int> LoaiHoatDong { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual Nguoi Nguoi { get; set; }
    }
}
