//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenNhanDang
    {
        public int MaPhanQuyenNhanDang { get; set; }
        public Nullable<int> KhuVuc { get; set; }
        public Nullable<int> PhongBan { get; set; }
        public Nullable<int> ChucVu { get; set; }
        public Nullable<int> Nguoi { get; set; }
        public Nullable<int> MaThietBiNhanDang { get; set; }
    }
}
