//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATINTimekeeping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Status
    {
        public Nullable<decimal> SOLUONG { get; set; }
        public int statusupdate { get; set; }
        public string SP_CODE { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string TieuDe { get; set; }
        public string trangthaimoi { get; set; }
    }
}
